### ISSUE TITLE
Write Tutorial about how to use Circles Account in Gnosis Safe App

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-handbook#8]
**Todo:**

- [x] Merge tutorial PR
- [x] Integrate tutorial in navigation sidebar
- [x] Make images look nicer (maybe there is something in docusaurus one can just use)

Related discussion: https://aboutcircles.com/t/use-gnosis-safe-as-circles-wallet/338/11

**Comment by louilinn** [comment]
Both issue 8 and 9 will be resolved in this PR: https://github.com/CirclesUBI/circles-handbook/pull/23
